[project]
name = "iceduck"
version = "0.0.1"
description = "DuckDB wrapper with iceberg writer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.2",
    "numpy>=2.2.4",
    "pyiceberg[duckdb,glue,pandas]>=0.9.0",
]
